# Generated by Django 5.2.7 on 2025-10-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tarea_familia_alter_tarea_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='codigo_invitacion',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
