# Generated by Django 5.2.7 on 2025-10-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_familia_codigo_invitacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='hora_fin',
            new_name='hora_termino',
        ),
        migrations.AddField(
            model_name='horario',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
