# Generated by Django 5.2.7 on 2025-11-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_familia_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='edad_minima',
            field=models.IntegerField(blank=True, help_text='Edad mínima requerida para realizar la tarea (solo si requiere_edad_minima está marcado).', null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='requiere_edad_minima',
            field=models.BooleanField(default=False, help_text='Marcar si esta tarea solo puede ser realizada por personas mayores a una edad específica.'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tiempo_requerido_minutos',
            field=models.IntegerField(default=30, help_text='Tiempo estimado para completar la tarea (en minutos).'),
        ),
    ]
