# Generated by Django 5.2.7 on 2025-11-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_tarea_edad_minima_tarea_requiere_edad_minima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='dias_recurrencia_csv',
            field=models.CharField(blank=True, help_text='Días de la semana en formato CSV (ej: LUN,MIE,VIE).', max_length=50, null=True),
        ),
    ]
