# Generated by Django 5.2.7 on 2025-11-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_tarea_dias_recurrencia_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha límite o de realización programada.', null=True),
        ),
    ]
