# Generated by Django 5.2.7 on 2025-11-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_tarea_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='responsable',
        ),
    ]
