# Generated by Django 5.2.7 on 2025-11-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_tarea_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_vencimiento',
        ),
    ]
